export const EditorNavItems = [
  { label: "Header Settings", href: "/editor/settings/header" },
  { label: "Footer Settings", href: "/editor/settings/footer" },
  { label: "Homepage Builder", href: "/builder/homepage" },
  { label: "All Pages", href: "/editor/allpages" },
  { label: "Mint New Page", href: "/editor/createpage" },
  // { label: "General Settings", href: "/editor/settings" },
];

export const TailwindColors = [
  "slate",
  "gray",
  "zinc",
  "neutral",
  "stone",
  "red",
  "orange",
  "amber",
  "yellow",
  "lime",
  "green",
  "emerald",
  "teal",
  "cyan",
  "sky",
  "blue",
  "indigo",
  "violet",
  "purple",
  "fuchsia",
  "pink",
  "rose",
];

export const colorWeights = [
  "50",
  "100",
  "200",
  "300",
  "400",
  "500",
  "600",
  "700",
  "800",
  "900",
  "950",
];

export const tailwindFontSize = [
  "text-xs",
  "text-sm",
  "text-base",
  "text-lg",
  "text-xl",
  "text-2xl",
  "text-3xl",
  "text-4xl",
  "text-5xl",
  "text-6xl",
  "text-7xl",
  "text-8xl",
  "text-9xl",
  "text-10xl",
];

export const tailwindFontWeight = [
  "font-thin",
  "font-extralight",
  "font-light",
  "font-normal",
  "font-medium",
  "font-semibold",
  "font-bold",
  "font-extrabold",
  "font-black",
];
